spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Db_Training
    username: localhost
    password: Password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
